version: 2.1
orbs:
  hugo: circleci/hugo@0.3.1
workflows:
  main:
    jobs:
      - hugo/build
      - deploy:
          requires:
            - hugo/build
          filters:
            branches:
              only: master
jobs:
  deploy:
    docker:
      - image: node:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "84:79:b2:27:c6:66:4d:f4:1b:a0:bd:e0:9e:2a:47:8e"
      - checkout
      - attach_workspace:
          at: built
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g gh-pages@latest
            git config --global user.email "$GH_EMAIL"
            git config --global user.name "$GH_USER"
      - run:
          name: Deploy built site to gh-pages branch
          command: gh-pages --dist built/public
